- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
- name: Install list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
    state: present
    update_cache: yes
- name: installing pip
  apt: 
    pkg: python3-pip
    state: present
- name: install certain python modules for docker
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
  - { name: docker, version: 2.0.0 }
