---
- name: deployment
  hosts: hosts
  become: true
  roles: 
    - docker
  tasks:
    - name: sync docker file dir
      synchronize: src=/home/johannes_esbjornsson/jenkinspipe dest=/tmp

    - name: Build an image 
      docker_image:
        force: yes
        path: /tmp/jenkinspipe
        name: test_pipe
        tag: latest
        state: present

    - name: Running the container
      docker_container:
        name: test_pipe
        image: test_pipe:latest
        state: started
        ports:
          - 80:80

